services:
  db:
    container_name: passkey-mysql
    build: .
    image: passkey_storage
    environment:
      MYSQL_ROOT_PASSWORD: '${MASTER_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
